BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `selfposts` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`session`	INTEGER NOT NULL,
	`time`	INTEGER NOT NULL,
	`channel`	TEXT NOT NULL,
	`message`	INTEGER,
	`ibp`	INTEGER DEFAULT 0
);
COMMIT;
